### ISSUE TITLE
Config

### ISSUE THREAD

**Issue by crookedneighbor** [haxiom/haxfred-slack#8]
Currently, we configure haxfred-slack with one key, `slack_token` which represents the Slack API token.

Instead, we should be configuring a slack object that contains a `token` key:

``` json
{
  "slack": {
    "token": "your api token"
  }
}
```

We should make this change before releasing v1

**Comment by lejeunerenard** [comment]
Makes sense to me.

**Comment by NickTomlin** [comment]
🎉🎉🎉TBT 2015 🎉 🎉🎉
